ALTER TABLE Users
DROP CONSTRAINT PK__Users__3214EC07E69C2FE6

ALTER TABLE Users
ADD CONSTRAINT PK_IdUsername PRIMARY KEY (Id, Username)

ALTER TABLE Users
ADD CONSTRAINT CH_CheckConstraintsIfPassIsAtLeastFiveSymbols CHECK (LEN([Password]) > 5)

ALTER TABLE Users
ADD CONSTRAINT DF_LastLogInTime  DEFAULT GETDATE()  FOR LastLogInTime