CREATE DATABASE OnLineStoreDatabase

USE OnLineStoreDatabase

CREATE TABLE Cities
(
 [CityID] INT PRIMARY KEY IDENTITY,
 [Name] VARCHAR(30) NOT NULL
)


CREATE TABLE Customers
(
 [CustomerID] INT PRIMARY KEY IDENTITY,
 [Name] VARCHAR(30) NOT NULL,
 [Birhday] DATE NOT NULL, 
 [CityID] INT FOREIGN KEY REFERENCES Cities(CityID)
)


CREATE TABLE Orders
(
 [OrderID] INT PRIMARY KEY IDENTITY,
 [CustomerID] INT FOREIGN KEY REFERENCES Customers(CustomerID)
)


CREATE TABLE ItemTypes
(
[ItemTypeID] INT IDENTITY PRIMARY KEY,
[Name] VARCHAR(50)
)


CREATE TABLE Items
(
 [ItemID] INT IDENTITY PRIMARY KEY,
 [Name] VARCHAR(50) NOT NULL,
 [ItemTypeID] INT FOREIGN KEY REFERENCES ItemTypes(ItemTypeID)
)

    
CREATE TABLE OrderItems
(
[OrderID] INT FOREIGN KEY REFERENCES Orders(OrderID),
[ItemID] INT FOREIGN KEY REFERENCES Items(ItemID),
CONSTRAINT PK_Orders_Items PRIMARY KEY (OrderID, ItemID)
)
